dist: bionic
sudo: false
cache:
    pip: true

language: python
python:
    - "3.5"
    - "3.6"

#install:
#    - python3 -m pip install pipenv
#    - pipenv install --dev --skip-lock
#
#script:
#    - pipenv run test

#deploy:
#    - python --version
matrix:
    include:
#        - python: "3.5"
#          install:
#              - python3 -m pip install pipenv
#              - pipenv install --dev --skip-lock
#          script:
#              - pipenv run test
#
#        - python: "3.6"
#          install:
#              - python3 -m pip install pipenv
#              - pipenv install --dev --skip-lock
#          script:
#              - pipenv run test
        - python: "3.5"
          env: BuildDocs=Yes
          install:
              - python3 -m pip install pipenv sphinx
              - pipenv install --skip-lock
          script:
              - pipenv run doctest

jobs:
    include:
        - stage: Docs
          install:
              - python3 -m pip install pipenv sphinx
              - pipenv install --skip-lock
          script:
              - pipenv run doctest

        - stage: Codecov
          install: pip install codecov
          script: codecov
    #    - # stage name not required, will continue to use `test`
    #      script: ./test 2
    #    - stage: deploy
    #      script: ./deploy
