dist: bionic
sudo: false
cache: pip
#    directories:
#        - $HOME/.cache/pip
#        - $HOME/.cache/pipenv

language: python
python:
    - "3.5"
    - "3.6"

install:
    - python3 -m pip install pipenv
    - pipenv install --dev --skip-lock

script:
    - pipenv run test

matrix:
    include:
        - name: Docs
          python: "3.5"
          install:
              - python3 -m pip install pipenv sphinx
              - pipenv install --skip-lock
          script:
              - pipenv run doctest

jobs:
    include:
#        - stage: Test
#          name: Docs
#          python: "3.5"
#          install:
#              - python3 -m pip install pipenv sphinx
#              - pipenv install --skip-lock
#          script:
#              - pipenv run doctest

        - stage: Codecov
          install: pip install codecov
          script: codecov
    #    - # stage name not required, will continue to use `test`
    #      script: ./test 2
    #    - stage: deploy
    #      script: ./deploy

#stages:
#    - Test
#    - Codecov
