dist: bionic
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pipenv

language: python
python:
    - "3.6"
    - "3.5"

install:
    - pip install pipenv
    - pipenv install --dev --skip-lock

script:
    - pipenv run test

jobs:
    include:
        - stage: Test
          name: Docs
#          python: "3.5"
          install:
              - pip install pipenv sphinx
              - pipenv install --skip-lock
          script:
              - pipenv run doctest
              - pipenv run build-docs

        - stage: Codecov
#          name: Codecov
#          python: "3.5"
#          install:
#              - pip install pipenv codecov
#              - pipenv install --dev --skip-lock
          before_script:
              - pip install codecov
          script:
              - pytest --cov
              - codecov --required
